# Generated by Django 3.2 on 2023-08-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230816_1043'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='Уникальность подписки',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='Уникальность подписки.'),
        ),
    ]
